### ISSUE TITLE
License of the Tilesets?

### ISSUE THREAD

**Issue by stefan2904** [elias-schuett/Online-Tile-Map-Editor#34]
I suggest adding a notice about the license of the provided tilesets.

**Comment by elias-schuett** [comment]
There is one here:
https://github.com/elias-schuett/Online-Tile-Map-Editor/blob/master/www/img/tilesets/licenses.txt

But I agree, it should probably be visible from within the editor itself.

**Comment by stefan2904** [comment]
ach, completely overlooked this file. thanks a lot.
